# Generated by Django 3.0.1 on 2019-12-29 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenca', models.BooleanField(default=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Calendario', to='calendario.Calendario', verbose_name='Dia')),
            ],
            options={
                'verbose_name': 'Batida de ponto',
                'verbose_name_plural': 'Batida de pontos',
                'ordering': ['dia'],
            },
        ),
    ]
