# Generated by Django 2.2.2 on 2020-01-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0002_frequencia_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='justificada',
            field=models.BooleanField(default=False),
        ),
    ]
