# Generated by Django 3.0.1 on 2019-12-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('dia', models.CharField(max_length=20, verbose_name='Dia da semana')),
                ('diaUtil', models.BooleanField(verbose_name='Dia útil')),
                ('observacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Calendário',
                'verbose_name_plural': 'Calendários',
                'ordering': ['data'],
            },
        ),
    ]
