# Generated by Django 2.2.2 on 2020-08-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remuneracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixaInicial', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Faixa Inicial')),
                ('faixaFinal', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Faixa Final')),
                ('percentualFiscal', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual Fiscal')),
                ('percentualEncarregada', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual Encarregada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=' Criado em ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=' Atualizado em ')),
            ],
            options={
                'verbose_name': 'Remuneração',
                'verbose_name_plural': 'Remunerações',
            },
        ),
    ]
