# Generated by Django 2.2.2 on 2020-08-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remuneracao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remuneracao',
            name='obs',
            field=models.CharField(default='Faixa 01', max_length=25, verbose_name='Observação'),
            preserve_default=False,
        ),
    ]
