# Generated by Django 3.0.1 on 2019-12-29 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducaoDiaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producao', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Produção do dia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendario.Calendario', verbose_name='Dia')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionario.Funcionario', verbose_name='Funcionário')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Produção',
                'verbose_name_plural': 'Produções',
            },
        ),
    ]
