# Generated by Django 3.0.1 on 2019-12-29 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperativa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=6, unique=True, verbose_name='Matrícula')),
                ('codigo', models.CharField(blank=True, max_length=8, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('apelido', models.CharField(blank=True, max_length=20, null=True, verbose_name='Apelido')),
                ('cpf', models.CharField(blank=True, help_text='Digite somente números', max_length=11, null=True, verbose_name='CPF')),
                ('setor', models.CharField(blank=True, max_length=30, null=True, verbose_name='Setor')),
                ('meta', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Meta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=' Criado em ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=' Atualizado em ')),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperativa', to='cooperativa.Cooperativa', verbose_name='Cooperativa')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to='funcionario.Funcionario', verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
