# Generated by Django 3.0.1 on 2019-12-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='codigo',
            field=models.CharField(max_length=8, unique=True, verbose_name='Código'),
        ),
    ]
