# Generated by Django 2.0.13 on 2020-02-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_auto_20191229_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(max_length=6, verbose_name='Matrícula'),
        ),
    ]
