# Generated by Django 2.2.2 on 2020-08-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0003_auto_20200215_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(choices=[('O', 'Operador'), ('F', 'Fiscal'), ('E', 'Encarregado')], default='O', max_length=1),
        ),
    ]
