# Generated by Django 2.2.2 on 2020-08-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0004_funcionario_funcao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remuneracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixaInicial', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Faixa Inicial')),
                ('faixaFinal', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Faixa Final')),
                ('percentualFiscal', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual Fiscal')),
                ('percentualEncarregada', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual Encarregada')),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Salário'),
        ),
    ]
