# Generated by Django 2.2.2 on 2020-08-30 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0005_auto_20200830_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remuneracao',
            options={'verbose_name': 'Remuneração', 'verbose_name_plural': 'Remunerações'},
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name=' Criado em '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name=' Atualizado em '),
        ),
    ]
