# Generated by Django 2.2.2 on 2020-08-30 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0006_auto_20200830_1825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Remuneracao',
        ),
    ]
